# Generated by Django 5.1.5 on 2025-01-25 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCarreraProfesional',
            fields=[
                ('codigoCP', models.IntegerField(primary_key=True, serialize=False)),
                ('nomCP', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TAlumno',
            fields=[
                ('codigo_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('peso', models.IntegerField()),
                ('talla', models.FloatField()),
                ('color', models.CharField(max_length=15)),
                ('prov', models.CharField(max_length=25)),
                ('fecha_ingreso_u', models.DateField()),
                ('codigoCP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.tcarreraprofesional')),
            ],
        ),
    ]
